### ISSUE TITLE
Only works with local filesystem storage.

### ISSUE THREAD

**Issue by tomatohater** [torchbox/wagtailmedia#24]
The codebase references `os.path` in a few places which pins this app to local file storage. Let's eventually enhance to work generically with any compatible storage backend.

**Comment by johnfraney** [comment]
@tomatohater If it helps make the transition easier, I can confirm that `os.path` works for path-like strings, even if the path doesn't exist on the local filesystem:

```
In [1]: import os

In [2]: filename = os.path.basename('s3://banana-bucket/plantain.txt')

In [3]: filename
Out[3]: 'plantain.txt'

In [4]: os.path.splitext(filename)[1][1:]
Out[5]: '.txt'
```

**Comment by richtier** [comment]
looks like this issue is either not valid or has since been fixed

https://github.com/torchbox/wagtailmedia/search?q=os.path&unscoped_q=os.path

`os.path` is being used for path-like string manipulation.

granted, in places maybe `urljoin` should be used instead - but this library should work with other backends.

**Comment by tomatohater** [comment]
Could be... I ran into an issue when I originally logged this. Could be resolved now.
