### ISSUE TITLE
MediaChooserPanel not compatible with Wagtail 2

### ISSUE THREAD

**Issue by DanSGraham** [torchbox/wagtailmedia#34]
The current implementation of MediaChooserPanel does not work in Wagtail 2 as the expected return value for bind_to_model is an object, not a type.

**Comment by DanSGraham** [comment]
I just commented out the bind_to_model method in the edit_handlers and it works fine for me. May not be the best way though.

**Comment by kaduuuken** [comment]
Works in my branch, if you use `BaseMediaChooserPanel` instead of `MediaChooserPanel`

**Comment by thibaudcolas** [comment]
From what I understand this particular issue isn't fixed. #40 would be the fix for this, or as @kaduuuken suggests people can also use `BaseMediaChooserPanel` instead of `MediaChooserPanel`.

At the moment the README only mentions `MediaChooserPanel`, so either the README needs to be updated or we need to merge the changes from #40.

I think my project uses the `AdminMediaChooser` widget directly with a standard `FieldPanel` – not entirely sure if/how that differs from the panel extending `BaseChooserPanel`.

**Comment by thibaudcolas** [comment]
From what I understand this particular issue isn't fixed. #40 would be the fix for this, or as @kaduuuken suggests people can also use `BaseMediaChooserPanel` instead of `MediaChooserPanel`.

At the moment the README only mentions `MediaChooserPanel`, so either the README needs to be updated or we need to merge the changes from #40.

I think my project uses the `AdminMediaChooser` widget directly with a standard `FieldPanel` – not entirely sure if/how that differs from the panel extending `BaseChooserPanel`.

**Comment by thibaudcolas** [comment]
Fixed in #40, I'll release this shortly.
