### ISSUE TITLE
Media file required to be uploaded again on edit

### ISSUE THREAD

**Issue by MechanisM** [torchbox/wagtailmedia#4]
I'm uploaded video, then I realised that I forgot to add width and height, so I navigated to edit video file, after entering width/height values, I've tried to submit my edit, but it says that video file is required. I need to reupload video file just to edit width/height.

**Comment by m1kola** [comment]
In Django 1.10 front-end validation was enabled by default.

In Wagtail this issue (https://github.com/torchbox/wagtail/issues/2897) was fixed by adding `novalidate` to all forms with a file field. So we can add `novalidate` into [this form](https://github.com/torchbox/wagtailmedia/blob/a19ec202bf3bec79e570bf21134fcf8fe3d7b570/wagtailmedia/templates/wagtailmedia/media/edit.html#L26). It should fix this issue, but I'm not sure. Would be great to check.

Thanks for reporting!
