### ISSUE TITLE
Include Media in templates

### ISSUE THREAD

**Issue by maxwaiyaki** [torchbox/wagtailmedia#44]
How do I include the media object and its attributes (like fileurl, name, tags, etc) in my template? Specifically, is there a special tag for wagtailmedia objects like we have for {% image %} in the wagtail templating specifications?

Thanks!

**Comment by thibaudcolas** [comment]
@maxwaiyaki I think you can access those attributes as properties of the field, and generate your own HTML for them. There is no ready-made tag (that I know of), because I think you need to do quite a bit more customisation for this with `audio`/`video` elements than you would with `img`. Accessing the properties manually would look like this:

```html
<object data="{{ my_custom_model.media.file.url }}"></object>
```

If anyone has better examples it would be great to document them in the README.

**Comment by thenewguy** [comment]
Here is an example until something more formal comes along:
```
<{{ media.type }} controls>
	{% for source in media.sources %}
		<source src="{{ source.src }}" type="{{ source.type }}" />
	{% endfor %}
</{{ media.type }}>
```
