### ISSUE TITLE
Extract needed info from media files, and don't require to enter it.

### ISSUE THREAD

**Issue by MechanisM** [torchbox/wagtailmedia#5]
It is not so hard to read media info from files like mp4 and mp3, so, why should I enter video title, duration(and calculate seconds)? It is also possible to extract Thumbnail.
eyeD3 or smth like this can be used for reading/writing tags.
Should I use custom media model to make it happen?

**Comment by m1kola** [comment]
Pull requests are always welcome ;)

**Comment by MechanisM** [comment]
Okay, I'll take a look into it. Btw, it would be nice to also have ability to see video thumbnails in admin list and some default "empty thumbnail" with wagtail logo.

**Comment by thenewguy** [comment]
This is really outside the scope of wagtailmedia.  There are several ways to solve this and no clear "best" due to the many cases to consider.  That doesn't mean there shouldn't be an nice package for it, just that it should probably be at a higher level than wagtailmedia.

It is a better fit for a custom media model as of now.  We are working to improve the pain points that make this difficult but I am going to close this issue.  If there is anything in particular you've run into, please share.

**Comment by Scotchester** [comment]
Sorry to resurrect an old closed issue, but I thought it might be better than a new issue for asking this question:

What were the considerations that led to making `duration` required in the first place? It doesn't seem to be required in practice, at least for our use case of using HTML `audio` and `video` elements, as demonstrated in the README.

**Comment by thenewguy** [comment]
@Scotchester that decision was before me

**Comment by zerolab** [comment]
By the looks of it, that comes from one of the original commits 4 years ago. Having been recently bitten by it in a demo, happy for a PR that makes that optional
