### ISSUE TITLE
Why isn't this in wagtail proper?

### ISSUE THREAD

**Issue by thenewguy** [torchbox/wagtailmedia#74]
Curious as to why this isn't included with Wagtail directly?  

It works well and audio/video is important enough on the web for dedicated html5 elements.  

Surely this is commonly required by every wagtail install?  I would imagine it would be more commonly used than wagtail.documents but maybe that is just me?

**Comment by zerolab** [comment]
We do take an approach of "build it when it is needed", rather than satisfy all use cases for all people. As such, this module came about when we had a need for one of our projects. By creating it as a separate package we could experiment and iterate faster. A number of things in Wagtail did start as separate packages (e.g. the API, modeladmin)

Will bring it up at the next core meeting.

**Comment by zerolab** [comment]
@thenewguy, on another note, are you per chance in the Wagtail slack? if so, can you DM me (zerolab). Or, if not, how can we get in touch?
